name: Oikos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50358
title: Oikos drafting consultants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#5988d6'
    - '#5b5a5f'
    - '#e6ddd6'
    - '#bcaa96'
  brandStrength: 0.12709602084942162
  lightness: 0.5193889308720827
  saturation: 0.4322413334157318
  rhythmicContrast: 0.35288940323516726
purpose: []
